name: stale-issues-prs

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          stale-issue-message: ''
          stale-pr-message: ''
          days-before-stale: 30
          days-before-close: 7
          days-before-pr-stale: 14
          days-before-pr-close: 7
          exempt-issue-labels: 'pinned'
          exempt-pr-labels: 'pinned'
